## YAML Template.
---
runtime: php55
api_version: 1

handlers:

- url: /helloworld.html
  mime_type: text/html
  static_files: helloworld.html
  upload: helloworld.html
  
# Serve images as static resources.
#- url: /
#  static_files: helloworld.html
#  upload: helloworld.html
#  
#- url: /(.+\.(gif|png|jpg))$
#  static_files: \1
#  upload: .+\.(gif|png|jpg)$
#  application_readable: true
#
## Serve php scripts.
#- url: /(.+\.php|html)$
#  script: \1