## YAML Template.
---
steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/my-hello-world-217616/my-feature', '.']
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/my-hello-world-217616/my-feature']